name: copy files
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: junghoonYu/TESTGithubAction/copy-file-action@master
      with:
        source: "files/test.txt"
        target: "test.txt"
