name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: hello world 출력!!
      run: echo Hello, world!
    - name: 디렉토리 출력!!
      run: ls -al
    - name: 파일생성!!
      run: date=$(date -d "now" "+%s"); touch /home/ubuntu/${date}      
    - name: 파이썬 버전 출력!!
      run: python -V
